### ISSUE TITLE
vue-cli-plugin-svg-sprite with Storybook

### ISSUE THREAD

**Issue by acopalipsis** [swisnl/vue-cli-plugin-svg-sprite#1]
How to use vue-cli-plugin-svg-sprite with storybook? webpack.config storybook can be extended. But how to write a config that vue-cli-plugin-svg-sprite worked??

**Comment by bbrala** [comment]
Good question, ill tag my colleage, he is currently on personal leave though so it might take a bit.

@JaZo could you check this out?

**Comment by JaZo** [comment]
Hi @acopalipsis, I personally have no experience with Storybook. I've had a look at their documentation (https://storybook.js.org/basics/guide-vue/) and it doesn't look like you can use Vue CLI plugins directly. However, you might give  https://github.com/storybooks/vue-cli-plugin-storybook a try and allow the Webpack plugin added by our Vue CLI plugin.

`vue.config.js`
```javascript
{
  pluginOptions: {
    storybook: {
      allowedPlugins: [
        'svg-sprite'
      ]
    }
  }
}
```

More details about using Storybook with Vue CLI 3: https://github.com/storybooks/storybook/issues/3267
