### ISSUE TITLE
how i inject style in sprite

### ISSUE THREAD

**Issue by x-amer-ngmx** [swisnl/vue-cli-plugin-svg-sprite#13]
Hi! I need to import stylus Style from all my VSG.

I do This:

vue.config.js
```js
{
  pluginOptions: {
    svgSprite: {
      dir: path.resolve(__dirname, 'src/assets/svg'),
      test: /\.(svg)(\?.*)?$/,
      loaderOptions: {
        stylus: {
          import: [path.resolve(__dirname, "src/assets/style/svg")]
        },
        extract: true,
        spriteFilename: 'img/icons.[hash:8].svg' // or 'img/icons.svg' if filenameHashing == false
      },
      pluginOptions: {
        plainSprite: true
      }
    }
  },
}
```
But it's not worked (((

**Comment by JaZo** [comment]
Hi @x-amer-ngmx, `loaderOptions` refers to the options of the underlying [svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader#configuration) package, you can't add extra loaders that way. If you like to add custom loaders for your SVG's, you have to fiddle with the Webpack config. Please see the [vue-cli docs](https://cli.vuejs.org/guide/webpack.html) for more information.

**Comment by JaZo** [comment]
More information about adding extra loaders: https://github.com/swisnl/vue-cli-plugin-svg-sprite#extra-loaders

**Comment by x-amer-ngmx** [comment]
Yes, thanks, I already figured it out. :ok_hand: 
And do not tell me how to embed the sprite in the html index :cry:

**Comment by JaZo** [comment]
You can set `extract: false` to let the sprite be automatically injected in the document body.
