### ISSUE TITLE
Bump svg-sprite-loader to latest version (4.1.6)

### ISSUE THREAD

**Issue by ingvoo** [swisnl/vue-cli-plugin-svg-sprite#6]
## Detailed description

Where I am deploying with docker I am facing an issue with a custom public path for the output of the `icons.svg` sprite.

It seems that this is(was) a known issue from svg-sprite-loader and now has been solved and released.

Here is the mentioned above issue https://github.com/kisenka/svg-sprite-loader/pull/340

So my question is if it's possible to bump svg-sprite-loader to latest version? I can do it myself and create a PR but I am not sure or aware of what I should test against when updating this package. 

## Possible implementation

Bump svg-sprite-loader dependency to latest version

**Comment by JaZo** [comment]
Hi @ingvijonasson, the svg-sprite-loader dependency is specified as `^4.0.0` so if you install it, you get the latest 4.x.x release (4.1.6 currently). If you installed the plugin some time ago and want a new release of the loader, you can easily update this package with NPM/Yarn e.g. `npm update vue-cli-plugin-svg-sprite` or `yarn upgrade vue-cli-plugin-svg-sprite`.
